### ISSUE TITLE
Compiling and running on a MacOS

### ISSUE THREAD

**Issue by nielsw2** [iridiumblue/korbie#1]
Thanks for sharing your fast geodesic visualizer. I was able to get it running on MacOS with the following small change:

on line 268 of c_calc.c I changed uint to int.

My compiler (clang) also warned that the file should have a .cc extension if you are compiling with a c++ compiler. The code looks like pure C to me so perhaps a C compiler is sufficient?

Other than that I had to run `pip install pyopengl pyqtgraph` to get the code to run on my machine. Might be worth mentioning that in the README.

One other thing: I found the code crashed if you the # Revolutions was set to 0

**Comment by iridiumblue** [comment]
That's fantastic!  I had gone to sleep just after I emailed you, and woke
up thinking I'd have to set up a 'hackintosh' to test on.  Then I opened my
email to find you had saved me from all that.

Yes - it's pure C code; I'll patch the bug where Revolutions=0 and update
the README.

Could I prevail on you to grab the binaries for me, so that other Mac users
can run without building?  With a bit of luck, this should work :
>  pip install pyinstaller
>  pyinstaller korbie.py
>  # a great many notifications will emerge, showing dependencies being
merged in
>  cp libkorbie.so dist/korbie        # pyinstaller doesn't know the shared
library needs to be included
>  cd dist/korbie                           # lot of stuff here, about 600
MB
>  tar cvf final.tgz *

The resultant final.tgz will be about 200MB, too big for github.   But if
you can upload it to google drive or something I'll grab it.   If this
gives you any trouble, of course, don't bother - you've already been very
generous with your time.

Thanks so much again, you really made my day!  I'll finish the Windows port
(which is an alien landscape to me too; bristling with exceptions and
differences) which is almost done.

best,
chris
